### ISSUE TITLE
Documentation "Package Manager"

### ISSUE THREAD

**Issue by inri13666** [eltrino/EltrinoOroCRMAmazonBundle#13]
"Package Manager" mentioned at "[README.md](https://github.com/eltrino/EltrinoOroCRMAmazonBundle/blob/master/README.md)" and ["Installation_Instructions"](https://github.com/eltrino/EltrinoOroCRMAmazonBundle/blob/master/Installation_Instructions/Installation_Instructions.md) are outdated and can't be used for OroCRM-Application 2+

Because "Package Manager" menu item was removed from "System".

I think will be better to re-use documentation from  ["How to Manage OroPlatform Extensions"](https://www.orocrm.com/documentation/current/cookbook/how-to-install-extension-from-command-line#using-the-package-manager)

**Comment by odi-um** [comment]
Fixed
