### ISSUE TITLE
Packagist not updated with latest changes

### ISSUE THREAD

**Issue by allieshq** [eltrino/EltrinoOroCRMAmazonBundle#23]
Hi,

The packagist repositories (https://packagist.orocrm.com/packages/eltrino/orocrm-amazon-bundle and https://packagist.org/packages/eltrino/orocrm-amazon-bundle) both show the latest release to be 2.1.1, meaning the latest updates aren't available for installation via composer.

Please could you add a tag for `2.2.0`?

Many thanks,
Dajve

**Comment by odi-um** [comment]
Hi @allieshq, we will finish up some testing during this week and will add appropriate tag for it.

p.s. Thank you for your contribution.

**Comment by allieshq** [comment]
Hi @odi-um 

Ah, no problem - we were just installing it on a client's installation and noticed that it hadn't pulled down all the changes from Packagist. Not to worry, though - we can hang fire a bit until we configure the sync.

And glad to help on the changes - we needed the functionality for the client's installation (and integration into our own bundles) so happy we could contribute. Thanks for putting the original integration out there in the first place =o)

Kind regards,
Dajve

**Comment by allieshq** [comment]
Hi @odi-um 

Just following up on this to see if there were any issues with the submission, or whether there was an ETA on pushing a tag through to Packagist?

Kind regards,
Dajve

**Comment by odi-um** [comment]
Hi, @allieshq 
I've created the tag, should be on the packagist already.
